# Generated by Django 4.1.1 on 2022-09-14 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("family", models.CharField(max_length=100, null=True)),
                ("id_code", models.CharField(max_length=100, null=True)),
                ("stud_code", models.CharField(max_length=100, null=True)),
                ("entrance_date", models.IntegerField(null=True)),
                (
                    "avatar",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        default=None, null=True, upload_to="avatars/"
                    ),
                ),
                ("phone", models.CharField(max_length=100, null=True)),
                ("bio", models.CharField(max_length=500, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
                (
                    "mode",
                    models.IntegerField(
                        choices=[(0, "supervisor"), (1, "student"), (2, "professor")],
                        default=1,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Announce",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                ("body", models.TextField(max_length=2500, null=True)),
                ("cover", models.ImageField(null=True, upload_to="announce/covers/")),
                ("date", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CircleType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "icon",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        null=True, upload_to="icons"
                    ),
                ),
                ("description", models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("icon", models.ImageField(null=True, upload_to="icons/contacttypes/")),
            ],
        ),
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "description",
                    models.TextField(default=None, max_length=1500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "icon",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        null=True, upload_to="icons"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                ("body", models.TextField(default=None, max_length=2500, null=True)),
                ("date", models.IntegerField(null=True)),
                (
                    "cover",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        null=True, upload_to="covers"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfessorGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                (
                    "description",
                    models.TextField(default=None, max_length=1500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "select which location to be displayed in app main page",
                            )
                        ],
                        null=True,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("description", models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("description", models.TextField(max_length=500, null=True)),
                ("file", models.FileField(null=True, upload_to="references")),
                (
                    "cover",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        null=True, upload_to="covers"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="posts/files/")),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("value", models.CharField(default=None, max_length=500, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coreapp.contacttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "logo",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        null=True, upload_to="logos"
                    ),
                ),
                ("description", models.TextField(max_length=500, null=True)),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coreapp.circletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=100, null=True)),
                (
                    "description",
                    models.CharField(default=None, max_length=500, null=True),
                ),
                ("time", models.IntegerField(default=None, null=True)),
                ("done", models.BooleanField(default=False)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "sent"), (1, "confirmed"), (2, "rejected")],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnounceRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=100, null=True)),
                (
                    "announce",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.announce",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announce",
            name="skills",
            field=models.ManyToManyField(to="coreapp.skill"),
        ),
        migrations.AddField(
            model_name="announce",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="circles",
            field=models.ManyToManyField(blank=True, to="coreapp.circle"),
        ),
        migrations.AddField(
            model_name="user",
            name="expertise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coreapp.expertise",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coreapp.professorgroup",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coreapp.location",
            ),
        ),
    ]
